name:                bimaru-client
version:             0.1.0.0
github:              "githubuser/bimaru-client"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/bimaru-client#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- unordered-containers
- repline
- process
- base64
- bytestring
- lens
- QuickCheck
- scientific
- string-conversions
- split
- text
- transformers
- wreq
- yaml
- vector

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  bimaru-client-1:
    main:                Main.hs
    source-dirs:         app1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bimaru-client
  bimaru-client-2:
    main:                Main.hs
    source-dirs:         app2
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bimaru-client
  bimaru-client-3:
    main:                Main.hs
    source-dirs:         app3
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bimaru-client

tests:
  bimaru-client-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bimaru-client
    - tasty
    - tasty-hunit
    - tasty-quickcheck
